sonar.projectKey=pes2526q2-12-gei-upc_healthy_way_frontend
sonar.organization=pes2526q2-12-gei-upc-h
sonar.projectName=Healthy Way - Frontend
sonar.host.url=https://sonarcloud.io
sonar.sources=lib
sonar.tests=test
sonar.test.inclusions=**/*_test.dart
sonar.exclusions=build/**, .dart_tool/**, **/*.g.dart, **/*.freezed.dart, **/*.config.dart, coverage/**, .metadata, android/build/**, android/.gradle/**, ios/Pods/**, ios/Flutter/Flutter.podspec
